# Generated by Django 6.0.5 on 2026-05-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
